### ISSUE TITLE
Not an issue, but there is no other way to contact you 

### ISSUE THREAD

**Issue by randomcmd** [0x111111/ezKrunker#8]
Hello 0x111111,
I’m wondering if you could maybe tell me the basics on how to write a chrome extension krunker hack since I’ve been trying to code my own mods for a couple of days now, but there are like 0 tutorials on how to do this. Also I looked through the files of the extension and can’t find any code I could work with.
Hope you could help me out a little!

**Comment by nuntax** [comment]
I was also wondering how to do this
